spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=medicareweb
spring.datasource.password=medicareweb

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.profiles.active=@spring.profiles.active@

logging.pattern.console=%msg%n

server.port=8081